spring.datasource.url=jdbc:postgresql://localhost:5432/ourMarketplace
#spring.datasource.username=LAnat
#spring.datasource.password=3815
spring.datasource.username=postgres
spring.datasource.password=168228123123

spring.data.jpa.repositories.enabled=false