spring.datasource.url=jdbc:postgresql://localhost:5432/ourMarketplace
spring.datasource.username=LAnat
spring.datasource.password=3815
#spring.datasource.username=postgres
#spring.datasource.password=168228123123

spring.data.jpa.repositories.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
queue.name = marketplace-queue

rabbitmq.queue.orders=orders