spring.datasource.url=jdbc:postgresql://localhost:5432/ourMarketplace
spring.datasource.username=postgres
spring.datasource.password=168228123123
spring.jpa.generate-ddl=true
spring.datasource.driver-class-name=org.postgresql.Driver
